server:
  port: 9533

spring:
  ai:
    dashscope:
      api-key: your-api-key
      chat:
        options:
          model: qwen-plus
      audio:
        synthesis:
          options:
            model: cosyvoice-v1
            response-format: mp3
            voice: longwan
            speed: 0.9
  application:
    name: voice-chat


logging:
  level:
    com.xc.voicechat: INFO
    org.springframework.web: INFO